### ISSUE TITLE
module.json is missing key info

### ISSUE THREAD

**Issue by Oshcakes** [kaelad02/show-secrets#1]
Looks like you used a template but did not replace `replaced by workflow`

**Comment by kaelad02** [comment]
You're right that I used a template. I found that the League had one that used GitHub's Actions to build the downloadable versions `module.json` and a `module.zip`. It's intentional that the committed version of `module.json` has that placeholder. When the workflow runs to generate the downloadable files attached to the releases, they've been replaced. The original file is not touched.

FYI... template I used is at https://github.com/League-of-Foundry-Developers/FoundryVTT-Module-Template
