### ISSUE TITLE
Not working with better rolls

### ISSUE THREAD

**Issue by JPD26** [kaelad02/show-secrets#3]
Hosting thru the forge and it doesn't seem to work with the better rolls module
![image](https://user-images.githubusercontent.com/101990071/159175014-8c310105-d064-4ce9-a64a-4b2c0bc13775.png)

though it does work when using the default 5e sheet for rolling
![image](https://user-images.githubusercontent.com/101990071/159175037-68696634-939f-48f3-8786-31e9aa1bfcf7.png)

Any plans to have it be compatible?

**Comment by kaelad02** [comment]
Better Rolls is constructing that chat message itself. But specifically for our purposes, it's the one that's calling `TextEditor.enrichHTML` and that's what this module modifies (so we can pass an option to not strip out secrets). I looked into the Better Rolls code and can see where it's happening, `RollFields#constructModelsFromField`, but I'm not sure how to change it since that class or function isn't exposed in some API.

I'll play around a little more, but it doesn't look promising.

**Comment by kaelad02** [comment]
Unfortunately it won't work with BR. We'd need to change BR to do the work to support this and as it's basically in maintenance mode now, I don't see that happening.
