### ISSUE TITLE
[Feature Suggestion] Additional label for "truesecret"

### ISSUE THREAD

**Issue by GhostwheelX** [kaelad02/show-secrets#4]
Might it be possible to add another label for things we also don't want to see as the DM?

While there might be things that we want to see that we don't want players to see in features, at other times we might want things to be in secret text not because they're actual secrets, but because the explanation is so long that we don't want it clogging up the chat every time (for example, in the case of a magic sword that has a super specific thing that comes up once in a while, but we don't want to see it every time the sword is swung).

Might it be possible to implement something like that?

**Comment by kaelad02** [comment]
I can see the value but there's also the [GM Notes](https://foundryvtt.com/packages/gm-notes) module does something similar already. It gives you a separate block of text, like the description, where the GM can keep notes and not even players can see them on owned actors.

Would it be okay if I closed this and we just use that other module instead?

**Comment by GhostwheelX** [comment]
Unfortunately when I tried to activate it, it didn't do anything or give me an option to add [secret] notes that only the GM could see.

Might it be possible to add that functionality to this module? If that's too much of a bother, feel free to close this issue.

EDIT: I found a fork that works, but unfortunately it doesn't have the functionality I'm looking for, where the GM notes are automatically output to chat when the item is rolled, unlike how this module works. Unless you go into the item and click on the "GM Notes" tab, you might entirely forget that you even ever wrote something in there.

**Comment by czajos89** [comment]
Only GM secret notes would be an extraordinary addition !!! Im no programmer and  I created this account just to l let you know. 
PLEASE make it happen 🙏

**Comment by kaelad02** [comment]
GM Notes has received some updates and is even compatible with v11. While it'd be nice for this module to have the feature, I tried updating the GM Secret Block module for v10 and ran into issues trying to add a new control to the Prosemirror editor. I'd have to do the same here and I already know how difficult it is without any help from Foundry's API to do it. It's just a bit out of scope for this module and better handled in GM Notes, especially since it's gotten some fixes and works in v11.
