### ISSUE TITLE
Reveal button not shown when chat card is all secret.

### ISSUE THREAD

**Issue by Oshcakes** [kaelad02/show-secrets#6]
This may be a core foundry bug but wanted to make you aware. Great module by the way, thanks for the v10 updates!
![image](https://user-images.githubusercontent.com/61471647/191779571-a66242e3-ea01-41be-bbdc-e92436325022.png)

**Comment by kaelad02** [comment]
I'm not able to reproduce it running v10.286. I made a copy of the Aboleth's tentacle attack and removed the part that was outside the secret block. Then I double-checked the HTML source to confirm, looked something like this (and only this):

```html
<section class="secret" id="secret-ID27xgPNBkauEfuS">
    <p>stuff in here</p>
</section>
```

One thing I noticed from using the Aboleth, which was from the dnd5e SRD compendium, was that the Reveal button didn't appear at first. If the item was created originally in v9, then the secret block won't have the `id` property like you see in the snippet above. And because it's missing `id`, I didn't see the Reveal button (it needs it to determine which block to reveal/hide). As soon as I edited the item's description and resave it, it got the `id` and the Reveal button appeared.

If the Bite from the first screenshot was originally created from v9 then that probably explains why. If you do any little update, even adding some text then removing it, that should add the `id` and then the Reveal button will appear. Can you confirm?

**Comment by Oshcakes** [comment]
Yes, that is exactly the case. Thanks

**Comment by Oshcakes** [comment]
Yes, that is exactly the case. Thanks
