### ISSUE TITLE
Broken with Pathfinder 2e 4.6.0

### ISSUE THREAD

**Issue by Wonton77** [kaelad02/show-secrets#7]
As of Pathfinder 2e module 4.6.0, Show Secrets appears to cause an issue where the "Damage" / "Half" / "Double" / etc buttons on a damage roll in chat no longer function.

**Comment by kaelad02** [comment]
I think I see the issue. The way I'm changing how the chat message is rendered is interfering with the way the pf2e system also changes things. I end up overriding whatever code the system wants to do, which is now where the code to handle those damage buttons lives. I just need to figure out how to change Foundry's base `ChatMessage` class instead of how I'm using libWrapper right now.

**Comment by kaelad02** [comment]
I released version 2.1.1 with this bug fix.
